### ISSUE TITLE
Chrome History file no longer identified

### ISSUE THREAD

**Issue by BowenMarmot** [Velocidex/SQLiteHunter#13]
The "History" file from chrome is no longer identified as a History Visits file.  The cause appears to be the removal of one of the tables.  

SQLECmd has been updated with this commit: https://github.com/EricZimmerman/SQLECmd/commit/61954a4e91b3bafabb3efbfa9d3591a2057df1bf

Tested this with recent versions of Edge and Chrome, by updating the JSON in the SPEC in a custom notebook.

**Comment by BowenMarmot** [comment]
Aaaaaand, I see that you have updated the definition file just as I was writing up this issue.

**Comment by scudette** [comment]
Haha yeah we hit the same issue too 😂
